# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: D’un bout à l’autre
email: romain@orreteguy.fr
phone: "+33652555647"
public_phone: "06 52 55 56 47"
description: |-
  Soutien scolaire pour le primaire et en français au collège, mais aussi
  compagnie sénior pour rompre la solitude.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://romain.orreteguy.fr" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
# theme: minima
plugins:
# - jekyll-feed
- jekyll-tailwind
# - jekyll-sitemap

page_excerpts: true

excerpt_separator: "<!--more-->"

collections:
  articles:
    output: true
    sort_by: date
    permalink: /articles/:title/

# Settings for the jekyll-tailwind plugin
tailwind:
  config: tailwind.config.js
  input: css/main.css
  output: _site/assets/css/main.css
  # postcss: config/postcss.config.js # default is nil
  # minify: true # defaults to false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - bin/
  - .gitignore
  - .gitattributes
  - .github/
  - .sass-cache/
  - .jekyll-cache/
  - .ruby-lsp/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "**/.keep"
  - css/
  - "./*.md"
  - tailwind.config.js
